### ISSUE TITLE
suggestion to include changing/printing working directory

### ISSUE THREAD

**Issue by melanieleung** [swcarpentry/r-novice-gapminder#755] opened 2021-11-01 22:02 UTC
for many workshop participants, this is their first time loading data into R, so it would be helpful to include in one of the first episodes how to print the working directory, and change it to a specific folder

**Comment by jcoliver** [comment] 2021-11-01 22:10
Thanks, @melanieleung . See also discussions in #276 and #332

**Comment by frank0434** [comment] 2021-12-10 03:53
Hi there, not sure if you have seen [this post](https://www.tidyverse.org/blog/2017/12/workflow-vs-script/) from Jennifer Bryan.  
It is titled _Project-oriented workflow_.
I am aware that this concept might add too much to the participant. 
But since this is part of "R for Reproducible Scientific Analysis", wondering if it is better to show participants the reproducible way from the start? 

There is a small yet super useful package called [**here**](https://cran.r-project.org/web/packages/here/index.html) that was developed by Kirill Müller and Jennifer Bryan. 
Wondering if it is worth introducing the `here` package and making the knowledge about directory changes in R as background information for participants to challenge themselves?

**Comment by naupaka** [comment] 2021-12-13 21:53
I think we want to advocate for the use of R project files as opposed to `setwd()`. Setting the working directory in code is very brittle. I think the `here` package is great, but perhaps a little out of scope for the lesson.

However, I do think the *concept* of working directories is important to address. This is often also discussed in the bash lessons in a typical SWC workshop.

**Comment by jcoliver** [comment] 2022-01-06 22:58
Addressed in #761

**Closed by jcoliver** 2022-01-06 22:58 UTC
Labels: help wanted, type:enhancement
