### ISSUE TITLE
Current release build broken - Rv4.0 incompatibilities?

### ISSUE THREAD

**Issue by marklcrowe** [swcarpentry/r-novice-gapminder#633] opened 2020-05-08 02:32 UTC
Hi, there looks to have been bugs introduced in the most recently build of episode 05-data-structures-part2. Specifically, the last table of the "Adding columns and rows in data frames" section and the first two of "Removing rows" are broken in the final .md output (NAs where there should be data, data, where there should be NAs). 

My guess is that it's a consequence of the build being performed with R4.0, with the switch to stringsAsFactors = FALSE on read.csv giving different dataframe structures and so unexpected outputs. And because it's a build issue rather than a code error, I can't lodge a pull request to try to fix it. 

Are you able to roll back to a previous version of this .md file until the episode has been updated enough to be compatible with R 4.0 please? At the moment, it's wrong for all versions of R!

Thanks very much

Cheers, Mark

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

If this issue is about a specific episode within a lesson, please provide its link or filename.

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate Hertweck (k8hertweck@gmail.com).  

---

**Comment by jcoliver** [comment] 2020-05-08 18:00
Thanks, @marklcrowe . We're looking into this now.

**Comment by jcoliver** [comment] 2020-05-20 19:14
This is indeed caused by the development of lesson materials for R versions < 4.0, while the Travis CI uses R 4.0 to build the lesson that is displayed. With the use of Travis CI, md files are no longer used for the display of lesson materials, so replacing the md files will not change what is displayed on the lesson site. The ideal options include revising the lesson material to (1) use all R 4.0, whereby the factor errors thrown by adding a new coat color go away and/or (2) add information about the varied behavior of `read.csv` between different versions of R.

**Comment by jcoliver** [comment] 2021-02-03 23:16
Stopgap PR in #684 for episodes 4 & 5, but longer term solution in the works.

**Comment by mlell** [comment] 2021-08-17 22:37
This is a proposed solution, among other things: #737

**Comment by naupaka** [comment] 2024-03-24 18:48
Closing as addressed with removal of factors

**Closed by naupaka** 2024-03-24 18:48 UTC
Labels: status:in progress, type:bug
