### ISSUE TITLE
Reference materials

### ISSUE THREAD

**Issue by sritchie73** [swcarpentry/r-novice-gapminder#1] opened 2015-04-21 04:17 UTC
Hi all, 

I'm not sure whether this is more appropriate as an issue or a pull request, but here is the repository for the gapminder lessons I developed for the February workshop we held in Melbourne: https://github.com/resbaz/r-novice-gapminder/ 

Also some acknowledgements and attributions: These materials were heavily based on materials originally written by @dfalster and @richfitz and modified by @dbarneche for a Software Carpentry R workshop run in Sydney last October (https://github.com/dbarneche/2014-10-31-USyd), and on some of the intermediate R materials (particularly the data structures lesson) written by @karthik (still part of the bc repo: https://github.com/swcarpentry/bc/tree/gh-pages/intermediate/r).

**Comment by naupaka** [comment] 2015-04-22 15:39
Awesome, thanks @sritchie73 for getting this process started. I think one way to do it would just be to have you open a pull request for the full set of materials to this repo, and then we can have subsequent changes be to streamline the material down to what is appropriate for a half day at the beginner level. These could be proposed as issues, and then interested people could take an issuer and make the code changes as needed.

Although come to think of it since your repo wasn't a fork of this one, a pull request might not work and we may have to do a more slightly complicated merge to make sure the commit history comes over. 

I'd be interested to hear what others think about the best approach to get this rolling.

**Comment by sritchie73** [comment] 2015-04-23 02:21
> Although come to think of it since your repo wasn't a fork of this one, a pull request might not work and we may have to do a more slightly complicated merge to make sure the commit history comes over.

That was really the motivating factor for submitting this as an issue. I have no idea how to submit a pull request since it's not a fork. I suppose you could set the repo as an upstream remote and pull that way?

Also I've been made aware that @hdashnow, @nfaux, @griffinp, and @cryptarch made substantial changes for their workshop a few weeks ago, so it may be better to pull from: https://github.com/COMBINE-Australia/r-novice-gapminder/

**Comment by naupaka** [comment] 2015-04-23 16:38
Ok, good to know. Not sure it's possible to do directly on GitHub, but I think setting that repo up as a remote, fetching, then perhaps using either cherry-pick or format-patch should work to do what we want ([Info here on SO](http://stackoverflow.com/questions/5120038/is-it-possible-to-cherry-pick-a-commit-from-another-git-repository)). I'll give other a couple days to add their thoughts on how to get this rolling.

**Comment by aammd** [comment] 2015-04-23 17:07
Hello everyone! Sorry I just noticed this conversation now. 
I was talking to @daisieh (Maintainer of the Git lesson repo) just yesterday about how best to bring in the existing gapminder lessons. She suggested the exact method that @naupaka just outlined: Clone from https://github.com/COMBINE-Australia/r-novice-gapminder/, add https://github.com/swcarpentry/r-novice-gapminder/ as a remote, then push. 

@naupaka my gut feeling is that we should just bring the COMBINE lessons in wholesale and then start some conversations on PRs and issues about any changes we want. I think that is both more straightforward than using git magic and also makes it possible for more people to contribute. After all, we know that it works -- it has been taught twice already! But perhaps there are advantages that I'm not seeing to the approach you suggest?

@sritchie73 I agree that the COMBINE lesson plan might be a better starting point, mostly because it seems shorter.

**Comment by aammd** [comment] 2015-04-23 17:29
@tomwright01 what are your thoughts? any objections to bringing in the COMBINE lesson and then discussing over it? We were thinking of doing so sometime tomorrow afternoon, North American time.

**Comment by tomwright01** [comment] 2015-04-23 18:34
Sorry all, I had forgotten to watch this repo.
Looks like the complete history from Rezbaz is included in the COMBINE repo. Adding this repo as a remote and doing a push should work great. Need to take a bit of care that everything is moved from the COMBINE:gh-pages branch to the master branch.

**Comment by dfalster** [comment] 2015-04-24 05:47
Hi Scott,

Thanks for the note acknowledging our contribution - much appreciated.

I thought it also worth posting a link to the original material @richfitz,
@dbarneche and I developed [web](
http://nicercode.github.io/2014-02-18-UTS/lessons/), [repo](
https://github.com/nicercode/2014-02-18-UTS/), in case some of that
material isuseful. For example, the plots are made with base R (which I
consider better for novices than ggplot).  Also the section on
[reproducible research](
http://nicercode.github.io/2014-02-18-UTS/lessons/90-reproducible/) can be
a nice way to wrap up, as it's mostly discussion.

Also, I would strongly recommend avoiding packrat in the novice lessons.

**Comment by hdashnow** [comment] 2015-04-24 06:06
@dfalster, we ran packrat at a recent workshop. I agree, it wasn't right for a novice audience. 

In retrospect we would have been much better off doing some simple manual folder setup at the start and leave it at that. You can still teach the same concepts of project organisation etc. without complicating it with extra installation and a whole bunch of folders that the participants wont use yet.

**Comment by hdashnow** [comment] 2015-04-24 06:08
@tomwright01 we did all the COMBINE development in gh-pages in order to make the entire thing student-facing. I would suggest deleting master and making gh-pages the default branch for the new repository.

**Comment by dfalster** [comment] 2015-04-24 06:23
@hdashnow, I think packrat might be overload, but I still think it can be useful to have some materials in folders to download (each folder being a new lesson). 

In one bootcamp i tried to let the materials build up, from one lesson to another. The problem was that if the students didn't quite follow in one lesson, they started the next already in trouble. In another bootcamp i gave out the prepared folders so that students started each lesson with exactly the right materials. This worked great. I (as instructor) knew what was in the project, fewer people got left behind.

**Comment by hdashnow** [comment] 2015-04-24 06:30
@dfalster, agreed.
In another workshop we cloned a separate repository that just contained data. Then had the students set up their Rstudio projects in that folder. That worked out nicely. We only had one student left behind out of ~40, and that was easily fixed. I think something along those lines would work for this as well.

**Comment by sritchie73** [comment] 2015-04-24 06:42
I toyed with the idea of packrat (hence why it's in the repo) but ultimately made the call not to teach it on the day because it was going to be too confusing to introduce too many concepts at once.

@dfalster the ggplot lesson has been really well received in both workshops we've ran it in (thanks to @nfaux's brilliant teaching). My suspicion is that ggplot is hard for those already experienced with base plot because its so different, but for novices its much of a muchness.

**Comment by hdashnow** [comment] 2015-04-24 06:44
Agreed. ggplot was a highlight. Any half day should definitely get to it! (kudos to @griffinp for her excellent demonstration at the latest workshop!)

**Comment by nfaux** [comment] 2015-04-24 06:47
Thanks Scott!!

I agree, packrat caused too many issues. However, I think the ProjectTemplate aspect is important but needs to reenforced within the lessons. So that it becomes part of the students workflow.

Cheers,
Noel Faux

**Comment by tomwright01** [comment] 2015-04-24 13:01
I see three main issues being discussed here:
1. Do we keep development in gh-pages branch or move it to master.
2. Should packrat content be included or removed (seems the consensus is to remove it).
3. ggplot or base graphics.

I suggest we import the COMBINE repository as it stands then open separate issues for each of these three conversations.

**Comment by naupaka** [comment] 2015-04-24 14:53
Hi all - Thanks for the good feedback and discussion. I agree with @tomwright01's assessment. Unless there are any other comments or objections, I'll pull in the COMBINE repo this afternoon and open these three points as issues for further discussion.

**Comment by aammd** [comment] 2015-04-24 21:29
@naupaka et al +1 and I'm really looking forward to hacking away at the content with all of you.

**Comment by dfalster** [comment] 2015-04-25 00:26
Sounds good

**Comment by naupaka** [comment] 2015-04-26 04:46
Great discussion, all. I've broken out the discussion points mentioned by @tomwright01 into three new issues ( #2 #3 #4 ), and imported the gapminder content from the COMBINE repo (onto a gh-pages branch). Closing this issue.

**Closed by naupaka** 2015-04-26 04:46 UTC
